"""Create chunks table

Revision ID: 65890b47867e
Revises: e626f317aef2
Create Date: 2026-09-24 16:02:36.813047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65890b47867e'
down_revision = 'e626f317aef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.CheckConstraint('position >= 0', name='ck_chunks_position_non_negative'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'position', name='uq_chunks_document_position')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunks')
    # ### end Alembic commands ###
